// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpxesqyymeilguosduoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtweGVzcXl5bWVpbGd1b3NkdW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDQ3MTcsImV4cCI6MjA3Mjg4MDcxN30.5e7PEglxLAGZH6luxYih6SumP-qFk6pe8xtIPdoOd_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});